---
title: "License"
output:
  workflowr::wflow_html:
    toc: false
    theme: journal
    highlight: textmate
    code_folding: hide
    df_print: paged
editor_options:
  chunk_output_type: console
---

This repository contains code and output of the analysis of mitochondria
DNA deletions data for the article [Shamanskiy, V. et al.,
2023](https://doi.org/10.1186/s12915-023-01606-1 "Shamanskiy, V. et al. (2023) Secondary structure of the human mitochondrial genome affects formation of deletions, BMC Biology, 21(1), p. 103. Available at: https://doi.org/10.1186/s12915-023-01606-1").

Please see file `CITATION` in the root of this GitHub repo that contains
the citation information.

To see the results of the analysis please visit the [analysis
website](https://github.com/mitoclub/GlobalStructure/index.html "Analysis website").

The code in this analysis is covered by the [GNU General Public License
v3.0](https://choosealicense.com/licenses/gpl-3.0/ "GPL-3.0 License")
and the written content on this website is covered by a [Creative
Commons
CC-BY](https://creativecommons.org/licenses/by/4.0/ "CC-BY License")
license.

The publications mentioned and datasets used are covered by their
respective licenses and usage agreements. Please refer to those sources
for details.
